on: [workflow_dispatch]

jobs:
  build:
    uses: petejohanson/zmk/.github/workflows/build-user-config.yml@core/zephyr-3.5-update

---
include:
  - board: nice_nano_v2
    shield: charybdis_left
  - board: nice_nano_v2
    shield: charybdis_right
  - board: nice_nano_v2
    shield: settings_reset
